/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package org.unisiga.view;

/**
 *
 * @author USUARIO
 */
public class MenuPrincipalView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MenuPrincipalView.class.getName());

    /**
     * Creates new form MenuPrincipalView
     */
    public MenuPrincipalView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        btnInscripcion = new javax.swing.JButton();
        btnRegistrarNota = new javax.swing.JButton();
        btnGestionEstudiantes = new javax.swing.JButton();
        btnGestionAsignaturas = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Sistema de Gestión Universitaria");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(142, 142, 142)
                .addComponent(jLabel1)
                .addContainerGap(471, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 90));

        btnInscripcion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/IncripcionEstudiante.png"))); // NOI18N
        btnInscripcion.setText("Inscribir Estudiante en Sección");
        getContentPane().add(btnInscripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 260, 40));

        btnRegistrarNota.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/RegistrarNota.png"))); // NOI18N
        btnRegistrarNota.setText("Registrar Nota");
        btnRegistrarNota.addActionListener(this::btnRegistrarNotaActionPerformed);
        getContentPane().add(btnRegistrarNota, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 260, 40));

        btnGestionEstudiantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/GestionEstudiantes.png"))); // NOI18N
        btnGestionEstudiantes.setText("Gestión de Estudiantes");
        getContentPane().add(btnGestionEstudiantes, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 260, 260, 40));

        btnGestionAsignaturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/GestionAsignaturas.png"))); // NOI18N
        btnGestionAsignaturas.setText("Gestión de Asignaturas");
        getContentPane().add(btnGestionAsignaturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, 260, 40));

        btnSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/iconos/Salir.png"))); // NOI18N
        btnSalir.setText("Salir");
        getContentPane().add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 400, 80, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarNotaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarNotaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarNotaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MenuPrincipalView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnGestionAsignaturas;
    public javax.swing.JButton btnGestionEstudiantes;
    public javax.swing.JButton btnInscripcion;
    public javax.swing.JButton btnRegistrarNota;
    public javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
